apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: px-backup
  name: call-home
  namespace: px-backup
data:
  enable: "true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: px-backup
  name: px-backup
  namespace: px-backup
spec:
  ports:
  - protocol: TCP
    port: 10002
    targetPort: 10002
    name: grpc
  - protocol: TCP
    port: 10001
    targetPort: 10001
    name: rest-api
  selector:
    app: px-backup
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: px-backup
  namespace: px-backup
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
     app: px-backup
  template:
    metadata:
      labels:
        app: px-backup
    spec:
      containers:
      - env:
        - name: PX_BACKUP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LICENSE_SERVER
          value: "uat"
        - name: ZUORA_ENDPOINT
          value: "https://rest.apisandbox.zuora.com"
        - name: BILLING_TIMEOUT_MINS
          value: "4"
        - name: BILLING_INTERVAL_MINS
          value: "2"
        - name: PX_BACKUP_DEFAULT_ORG
          value: "default"
        image: docker.io/portworx/px-backup:1.2.2
        imagePullPolicy: Always
        name: px-backup
        ports:
        - containerPort: 10002
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 10001
          initialDelaySeconds: 13
          timeoutSeconds: 1
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 10001
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 60
        resources:
         requests:
           memory: "3Gi"
         limits:
           memory: "3Gi"
           # volumeMounts:
           #   - name: cert-volume
           #     mountPath: /etc/cert-volume
        command:
        - /px-backup
        - start
        - --datastoreEndpoints=etcd:http://etcd-0.etcd-headless:2379,etcd:http://etcd-1.etcd-headless:2379,etcd:http://etcd-2.etcd-headless:2379
          # - --datastoreEndpoints=etcd:https://etcd-0.etcd:2379,etcd:https://etcd-1.etcd:2379,etcd:https://etcd-2.etcd:2379
          # - --datastore-ca-file=/etc/cert-volume/ca.crt
          # - --datastore-cert-file=/etc/cert-volume/cert.pem
          # - --datastore-key-file=/etc/cert-volume/key.pem
      serviceAccountName: px-backup-account
      # volumes:
      #   - name: cert-volume
      #     secret:
      #       secretName: px-backup-etcd-certs
